local lightspeed = require("lightspeed")
lightspeed.setup({jump_to_unique_chars = {safety_timeout = 400}, match_only_the_start_of_same_char_seqs = true, limit_ft_matches = 5})
vim.cmd("silent! unmap s")
vim.keymap.set("n", "t", "<Plug>Lightspeed_s", {remap = true})
vim.keymap.set("n", "T", "<Plug>Lightspeed_S", {remap = true})
vim.keymap.set("n", "f", "<Plug>Lightspeed_f", {remap = true})
vim.keymap.set("n", "F", "<Plug>Lightspeed_F", {remap = true})
return vim.keymap.set("n", ":", "<Plug>Lightspeed_;_ft", {remap = true})
